import Router from "./components/Router";
import Navbar from "./components/common/Navbar";

function App() {
  return (
    <>
      <div className="App">
        <Navbar />

        <Router />
        <div>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
        </div>
      </div>
    </>
  );
}

export default App;
