import Router from "./components/Router";

function App() {
  return (
    <>
      <div className="App">
        <Router />
        <>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
          <p>temp</p>
        </>
      </div>
    </>
  );
}

export default App;
