import { useAuthContext } from "../util/AuthState";

const Home = () => {
  const {
    authentication: [authenticated],
    verification: [verified],
  } = useAuthContext();

  return (
    <>
      <div>
        Homepage contents go here:
        <button
          onClick={() => {
            console.log(authenticated, verified);
          }}
        >
          a
        </button>
        <div>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
          <p>TEMP</p>
        </div>
      </div>
    </>
  );
};

export default Home;
